version: '3.8'

services:
  cms_postgres:
    image: postgres:latest
    container_name: my-postgres-paytm-final
    environment:
      POSTGRES_DB: paytm-app
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data